spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://119.27.176.115:10199/edu
    username: root
    password: abc123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


logging:
  config: classpath:logback-spring.xml

server:
  error:
    whitelabel:
      enabled: false
    include-message: always

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
      limit: 100
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 139.9.113.206
      port: 6379