spring:
  profiles:
    active: pro
  datasource:
    url: jdbc:mysql://119.27.176.115:10199/edu?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF8
    username: root
    password: abc123456
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  config: classpath:logback-spring.xml

server:
  error:
    whitelabel:
      enabled: false
    include-message: always

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
      limit: 100
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 139.9.113.206
      port: 6379
